# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SigmaXC <- function(rho, SigmaX) {
    .Call('_SIVCMTest_SigmaXC', PACKAGE = 'SIVCMTest', rho, SigmaX)
}

knC <- function(x, h) {
    .Call('_SIVCMTest_knC', PACKAGE = 'SIVCMTest', x, h)
}

locallinear0C <- function(p, x0, hx, x, y) {
    .Call('_SIVCMTest_locallinear0C', PACKAGE = 'SIVCMTest', p, x0, hx, x, y)
}

locallinear1C <- function(p, x0, hy, x, y) {
    .Call('_SIVCMTest_locallinear1C', PACKAGE = 'SIVCMTest', p, x0, hy, x, y)
}

dlogetaC <- function(xb, y, hy) {
    .Call('_SIVCMTest_dlogetaC', PACKAGE = 'SIVCMTest', xb, y, hy)
}

cseffC <- function(x, y, beta, hx, hy) {
    .Call('_SIVCMTest_cseffC', PACKAGE = 'SIVCMTest', x, y, beta, hx, hy)
}

allcseffC <- function(x, ally, m, tm, s, beta, hx, hy, h) {
    .Call('_SIVCMTest_allcseffC', PACKAGE = 'SIVCMTest', x, ally, m, tm, s, beta, hx, hy, h)
}

sumseffC <- function(x, ally, m, tm, s, beta, hx, hy, h) {
    .Call('_SIVCMTest_sumseffC', PACKAGE = 'SIVCMTest', x, ally, m, tm, s, beta, hx, hy, h)
}

gestC <- function(h1, x, betaest, vec_allxb, vec_ally, gest) {
    .Call('_SIVCMTest_gestC', PACKAGE = 'SIVCMTest', h1, x, betaest, vec_allxb, vec_ally, gest)
}

delC <- function(x, xdel, n) {
    .Call('_SIVCMTest_delC', PACKAGE = 'SIVCMTest', x, xdel, n)
}

cvC <- function(vh, x, ally, betaest, vec_allxb, vec_y, vec_cv, gest, CV) {
    .Call('_SIVCMTest_cvC', PACKAGE = 'SIVCMTest', vh, x, ally, betaest, vec_allxb, vec_y, vec_cv, gest, CV)
}

Q <- function(M, VX, VY, W) {
    .Call('_SIVCMTest_Q', PACKAGE = 'SIVCMTest', M, VX, VY, W)
}

kroneckerC <- function(M1, M2) {
    .Call('_SIVCMTest_kroneckerC', PACKAGE = 'SIVCMTest', M1, M2)
}

TnC <- function(U, angle, n, M) {
    .Call('_SIVCMTest_TnC', PACKAGE = 'SIVCMTest', U, angle, n, M)
}

NMCTnC <- function(U, En, angle, Cn, n, M) {
    .Call('_SIVCMTest_NMCTnC', PACKAGE = 'SIVCMTest', U, En, angle, Cn, n, M)
}

TrueNMCTnC <- function(U, En, angle, n, M) {
    .Call('_SIVCMTest_TrueNMCTnC', PACKAGE = 'SIVCMTest', U, En, angle, n, M)
}

BootTnC <- function(NewU, angle, n, M) {
    .Call('_SIVCMTest_BootTnC', PACKAGE = 'SIVCMTest', NewU, angle, n, M)
}

CnC <- function(X, n) {
    .Call('_SIVCMTest_CnC', PACKAGE = 'SIVCMTest', X, n)
}

PatTnC <- function(n, M, h, U0, DisKF, delta) {
    .Call('_SIVCMTest_PatTnC', PACKAGE = 'SIVCMTest', n, M, h, U0, DisKF, delta)
}

